# House Prediction

##### Downloading the data


In [8]:
import pandas as pd
import numpy as np
df = pd.read_csv("data/USA Housing Dataset.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-09 00:00:00,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0,9245-9249 Fremont Ave N,Seattle,WA 98103,USA
1,2014-05-09 00:00:00,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0,33001 NE 24th St,Carnation,WA 98014,USA
2,2014-05-09 00:00:00,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0,7070 270th Pl SE,Issaquah,WA 98029,USA
3,2014-05-09 00:00:00,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0,820 NW 95th St,Seattle,WA 98117,USA
4,2014-05-10 00:00:00,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0,10834 31st Ave SW,Seattle,WA 98146,USA


In [9]:
other_input = ['bedrooms', 'bathrooms', 'floors', 'condition']
to_scale = ['sqft_living','sqft_lot','sqft_above','yr_built']

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(df[to_scale])
scaled_input = scaler.transform(df[to_scale])
scaled_input

array([[-0.83942704, -0.37113768, -0.57049052,  1.24767028],
       [ 1.45854474,  4.03463216,  1.98385045,  1.21411812],
       [ 5.35465145,  3.21470057,  5.32771499,  1.3147746 ],
       ...,
       [ 0.90494245, -0.21419296,  1.36848649,  1.28122244],
       [-0.05602757, -0.22489754, -0.88397782,  0.10689686],
       [-0.68274715, -0.18386333, -0.3963309 ,  0.64373141]],
      shape=(4140, 4))

In [32]:
all = np.concatenate((scaled_input, df[other_input].values), axis = 1)
model = LinearRegression().fit(all, df['price'])
model

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [35]:
prediction = model.predict([[0.56,0.34,0.45,0.65,1,1,1,3]])
prediction

array([710671.9953973])

In [41]:
prediction = model.predict(df[['bedrooms', 'bathrooms', 'floors', 'condition','sqft_living','sqft_lot','sqft_above','yr_built']])
prediction

c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([9.60965048e+07, 9.78500250e+09, 7.81316715e+09, ...,
       3.88580929e+08, 3.56193319e+08, 5.05485348e+08], shape=(4140,))

In [42]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mean_absolute_error(df['price'], prediction)

878544287.9745785